### ISSUE TITLE
Plugin cannot import all torrent files at once

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT-plugin-migratetorrentapp#1]
**Describe the bug**
The plugin freezes the migration of torrents - it pretends that it work, but the window with the messages about migration of torrent files showing import of one file for hours. Window need to be closed and restart the migration. Then it will freeze again, but a little further - for example, not on the 300th file, but on the 500th.

**To Reproduce**
Just start torrents' migration.

**Expected behavior**
I want to import all my 4000+ torrents from uTorrent at one thread, not at thousands.

**Desktop**
 - OS: Windows 7 Enterprise SP1
 - uTorrent: 3.5.5 (45311)
 - BiglyBT: 2.2.0.2
 - Migrate plugin: 0.3.1

**Comment by Qwest8K** [comment]
If someone reads this:
I have a suspicion that migration is buggy if there is a capital letter "E" in the name of the torrent.

**Comment by Qwest8K** [comment]
Another clarification - is that if the capital letter "E" is at the very beginning of the torrent name, then the migration freeze and needs to be reloaded.

**Comment by TuxPaper** [comment]
I can't seem to reproduce.  I tried a torrent file starting with capital "E", with a torrent name starting with "E", with files in it that started with "E" and it all went smoothly :(

Do you have any logs from `%APPDATA\BiglyBT\logs` starting with the name `ut_Migrate_Secret_`?  Perhaps they might provide some clues (probably at the end of the log file).   Don't attach the secret file here.  The corresponding "Shareable" file should have all secret stuff hidden, and is probably safe to attach here if you want, but first make sure there's no personal information you'd not want seen.

**Comment by MasTech** [comment]
Wiped for a fresh install. Will attempt migration this weekend to get what you need.

**Comment by MasTech** [comment]
Been a long week. After a fresh install I still repro'd but found no logs with ut_Migrate_Secret_.

From BGs main log:

```
[17:32:27] [stderr] DEBUG::Thu Aug 26 17:32:27 CDT 2021::com.biglybt.core.util.DebugLight::printStackTrace::35:
[17:32:27] [stderr]   java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 55
\QD:\peer\in\Eastland Collection\E
                                ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2619)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2142)
	at com.biglybt.plugins.migratetorrentapp.Utils.wrapSubString(Utils.java:75)
	at com.biglybt.plugins.migratetorrentapp.Utils.getErrorAndHideStuff(Utils.java:114)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.migrateNow(Importer_uTorrent.java:403)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.lambda$3(Importer_uTorrent.java:279)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1011)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl$2.run(UtilitiesImpl.java:375)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
```
```
[17:31:19] [stderr] DEBUG::Thu Aug 26 17:31:19 CDT 2021::com.biglybt.core.util.DebugLight::printStackTrace::35:
[17:31:19] [stderr]   java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 23
\QD:\peer\in\EModel\E
                       ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2619)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2142)
	at com.biglybt.plugins.migratetorrentapp.Utils.wrapSubString(Utils.java:75)
	at com.biglybt.plugins.migratetorrentapp.Utils.getErrorAndHideStuff(Utils.java:114)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.migrateNow(Importer_uTorrent.java:403)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.lambda$3(Importer_uTorrent.java:279)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1011)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl$2.run(UtilitiesImpl.java:375)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[17:31:19] [stderr] 
```
```
[17:49:48] [stderr] DEBUG::Thu Aug 26 17:49:48 CDT 2021::com.biglybt.core.util.DebugLight::printStackTrace::35:
[17:49:48] [stderr]   java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 22
\QG:\ut\Eddy Collection\E
                      ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2619)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2142)
	at com.biglybt.plugins.migratetorrentapp.Utils.wrapSubString(Utils.java:75)
	at com.biglybt.plugins.migratetorrentapp.Utils.getErrorAndHideStuff(Utils.java:114)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.migrateNow(Importer_uTorrent.java:403)
	at com.biglybt.plugins.migratetorrentapp.utorrent.Importer_uTorrent.lambda$3(Importer_uTorrent.java:279)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1011)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl$2.run(UtilitiesImpl.java:375)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
```
Eventually worked around by using BEncode Editor to change the case of every "E" to "e". The imports finished perfectly after.

**Comment by TuxPaper** [comment]
Thank you.  This debug is very useful.

**Comment by Qwest8K** [comment]
I tried to transfer torrents from uTorrent to BiglyBT with a plugin, which was downloaded by BiglyBT installer, which I downloaded a several hours ago. This time migrate plugin imported my around 5,000 torrents without freezing.

**Comment by as-muncher** [comment]
Has this issue been fixed?  I'm using BiglyBT version 2.8.0.0

**Comment by enderandpeter** [comment]
I was hoping someone could help me understand how to use this plugin. I would love to try it. Do I need to build it from source code? If so, would anyone be so kind as to provide instructions?

I am seeing descriptions for this app online saying that the migration utility is built-in, but I am not finding it...

The [main page](https://www.biglybt.com/) says:

> 2019/08/13: BiglyBT's installers now include an [uTorrent and BitTorrent client migration plugin](https://github.com/BiglySoftware/BiglyBT-plugin-migratetorrentapp). No need to manually re-add all your torrents and settings. 

I would greatly appreciate assistance installing/activating this plugin. Thank you very much.

# Update 2023-05-20

Happy to say I got this to work. I'm using Windows, by the way. For the built-in plugin to appear, I had to reinstall freshly from the Stub installer. When doing so, the installer presented me with options for plugins to install, including the one for uTorrent migration. Now I see this option in the Tools menu.

When I first used it, it crashed. However, I accidentally made it migrate settings which I did not mean, as I only intended to migrate the torrents. I relaunched the program, deselected the box for migrating settings, and this time all my torrents migrated without issue. Thank you!
